---
- name: Check if docker or docker-ce are installed
  yum:
    list: installed
  register: installed_packages
- debug:
    var: item
  with_items:
    - "{{installed_packages|json_query(filter_docker)}}"
    - "{{installed_packages|json_query(filter_docker_ce)}}"
  vars:
    filter_docker: "results[?name=='docker']"
    filter_docker_ce: "results[?name=='docker-ce']"
  register: is_docker_installed

- include_tasks: tuned.yml
  when: '"k8s" in group_names or is_docker_installed.results'
- include_tasks: swap.yml
  when: '"k8s" in group_names or is_docker_installed.results'
- include_tasks: hostname.yml
- include_tasks: sudo.yml